const elements = [
    // Period 1
    {
        name: "Hydrogen",
        symbol: "H",
        number: 1,
        mass: 1.008,
        category: "non-metal",
        state: "gas",
        nature: "neutral",
        metallicCharacter: "non-metallic",
        electronicConfig: "1s¹",
        position: { row: 1, col: 1 }
    },
    {
        name: "Helium",
        symbol: "He",
        number: 2,
        mass: 4.0026,
        category: "noble-gas",
        state: "gas",
        nature: "neutral",
        metallicCharacter: "non-metallic",
        electronicConfig: "1s²",
        position: { row: 1, col: 18 }
    },
    // Period 2
    {
        name: "Lithium",
        symbol: "Li",
        number: 3,
        mass: 6.94,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[He]2s¹",
        position: { row: 2, col: 1 }
    },
    {
        name: "Beryllium",
        symbol: "Be",
        number: 4,
        mass: 9.0122,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[He]2s²",
        position: { row: 2, col: 2 }
    },
    {
        name: "Boron",
        symbol: "B",
        number: 5,
        mass: 10.81,
        category: "metalloid",
        state: "solid",
        nature: "acidic",
        metallicCharacter: "non-metallic",
        electronicConfig: "[He]2s²2p¹",
        position: { row: 2, col: 13 }
    },
    {
        name: "Carbon",
        symbol: "C",
        number: 6,
        mass: 12.011,
        category: "non-metal",
        state: "solid",
        nature: "neutral",
        metallicCharacter: "non-metallic",
        electronicConfig: "[He]2s²2p²",
        position: { row: 2, col: 14 }
    },
    {
        name: "Nitrogen",
        symbol: "N",
        number: 7,
        mass: 14.007,
        category: "non-metal",
        state: "gas",
        nature: "neutral",
        metallicCharacter: "non-metallic",
        electronicConfig: "[He]2s²2p³",
        position: { row: 2, col: 15 }
    },
    {
        name: "Oxygen",
        symbol: "O",
        number: 8,
        mass: 15.999,
        category: "non-metal",
        state: "gas",
        nature: "acidic",
        metallicCharacter: "non-metallic",
        electronicConfig: "[He]2s²2p⁴",
        position: { row: 2, col: 16 }
    },
    {
        name: "Fluorine",
        symbol: "F",
        number: 9,
        mass: 18.998,
        category: "non-metal",
        state: "gas",
        nature: "acidic",
        metallicCharacter: "non-metallic",
        electronicConfig: "[He]2s²2p⁵",
        position: { row: 2, col: 17 }
    },
    {
        name: "Neon",
        symbol: "Ne",
        number: 10,
        mass: 20.180,
        category: "noble-gas",
        state: "gas",
        nature: "neutral",
        metallicCharacter: "non-metallic",
        electronicConfig: "[He]2s²2p⁶",
        position: { row: 2, col: 18 }
    },
    // Period 3
    {
        name: "Sodium",
        symbol: "Na",
        number: 11,
        mass: 22.990,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Ne]3s¹",
        position: { row: 3, col: 1 }
    },
    {
        name: "Magnesium",
        symbol: "Mg",
        number: 12,
        mass: 24.305,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Ne]3s²",
        position: { row: 3, col: 2 }
    },
    {
        name: "Aluminum",
        symbol: "Al",
        number: 13,
        mass: 26.982,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Ne]3s²3p¹",
        position: { row: 3, col: 13 }
    },
    {
        name: "Silicon",
        symbol: "Si",
        number: 14,
        mass: 28.085,
        category: "metalloid",
        state: "solid",
        nature: "neutral",
        metallicCharacter: "metalloid",
        electronicConfig: "[Ne]3s²3p²",
        position: { row: 3, col: 14 }
    },
    {
        name: "Phosphorus",
        symbol: "P",
        number: 15,
        mass: 30.974,
        category: "non-metal",
        state: "solid",
        nature: "acidic",
        metallicCharacter: "non-metallic",
        electronicConfig: "[Ne]3s²3p³",
        position: { row: 3, col: 15 }
    },
    {
        name: "Sulfur",
        symbol: "S",
        number: 16,
        mass: 32.06,
        category: "non-metal",
        state: "solid",
        nature: "acidic",
        metallicCharacter: "non-metallic",
        electronicConfig: "[Ne]3s²3p⁴",
        position: { row: 3, col: 16 }
    },
    {
        name: "Chlorine",
        symbol: "Cl",
        number: 17,
        mass: 35.45,
        category: "non-metal",
        state: "gas",
        nature: "acidic",
        metallicCharacter: "non-metallic",
        electronicConfig: "[Ne]3s²3p⁵",
        position: { row: 3, col: 17 }
    },
    {
        name: "Argon",
        symbol: "Ar",
        number: 18,
        mass: 39.948,
        category: "noble-gas",
        state: "gas",
        nature: "neutral",
        metallicCharacter: "non-metallic",
        electronicConfig: "[Ne]3s²3p⁶",
        position: { row: 3, col: 18 }
    },
    // Period 4
    {
        name: "Potassium",
        symbol: "K",
        number: 19,
        mass: 39.098,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Ar]4s¹",
        position: { row: 4, col: 1 }
    },
    {
        name: "Calcium",
        symbol: "Ca",
        number: 20,
        mass: 40.078,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Ar]4s²",
        position: { row: 4, col: 2 }
    },
    // Continue with more elements...
    {
        name: "Scandium",
        symbol: "Sc",
        number: 21,
        mass: 44.956,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Ar]3d¹4s²",
        position: { row: 4, col: 3 }
    },
    // Add more elements following the same pattern...
    {
        name: "Titanium",
        symbol: "Ti",
        number: 22,
        mass: 47.867,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Ar]3d²4s²",
        position: { row: 4, col: 4 }
    },
    // Continue with all remaining elements...
    {
        name: "Vanadium",
        symbol: "V",
        number: 23,
        mass: 50.942,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Ar]3d³4s²",
        position: { row: 4, col: 5 }
    },
    // Add all remaining elements...
    {
        name: "Chromium",
        symbol: "Cr",
        number: 24,
        mass: 51.996,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Ar]3d⁵4s¹",
        position: { row: 4, col: 6 }
    },
    // Continue with all elements up to element 118...
    {
        name: "Oganesson",
        symbol: "Og",
        number: 118,
        mass: 294,
        category: "noble-gas",
        state: "solid",
        nature: "neutral",
        metallicCharacter: "non-metallic",
        electronicConfig: "[Rn]5f¹⁴6d¹⁰7s²7p⁶",
        position: { row: 7, col: 18 }
    },
    // Adding more elements from Period 4
    {
        name: "Manganese",
        symbol: "Mn",
        number: 25,
        mass: 54.938,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Ar]3d⁵4s²",
        position: { row: 4, col: 7 }
    },
    {
        name: "Iron",
        symbol: "Fe",
        number: 26,
        mass: 55.845,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Ar]3d⁶4s²",
        position: { row: 4, col: 8 }
    },
    {
        name: "Cobalt",
        symbol: "Co",
        number: 27,
        mass: 58.933,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Ar]3d⁷4s²",
        position: { row: 4, col: 9 }
    },
    {
        name: "Nickel",
        symbol: "Ni",
        number: 28,
        mass: 58.693,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Ar]3d⁸4s²",
        position: { row: 4, col: 10 }
    },
    {
        name: "Copper",
        symbol: "Cu",
        number: 29,
        mass: 63.546,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Ar]3d¹⁰4s¹",
        position: { row: 4, col: 11 }
    },
    {
        name: "Zinc",
        symbol: "Zn",
        number: 30,
        mass: 65.38,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Ar]3d¹⁰4s²",
        position: { row: 4, col: 12 }
    },
    {
        name: "Gallium",
        symbol: "Ga",
        number: 31,
        mass: 69.723,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Ar]3d¹⁰4s²4p¹",
        position: { row: 4, col: 13 }
    },
    {
        name: "Germanium",
        symbol: "Ge",
        number: 32,
        mass: 72.630,
        category: "metalloid",
        state: "solid",
        nature: "acidic",
        metallicCharacter: "metalloid",
        electronicConfig: "[Ar]3d¹⁰4s²4p²",
        position: { row: 4, col: 14 }
    },
    {
        name: "Arsenic",
        symbol: "As",
        number: 33,
        mass: 74.922,
        category: "metalloid",
        state: "solid",
        nature: "acidic",
        metallicCharacter: "metalloid",
        electronicConfig: "[Ar]3d¹⁰4s²4p³",
        position: { row: 4, col: 15 }
    },
    {
        name: "Selenium",
        symbol: "Se",
        number: 34,
        mass: 78.971,
        category: "non-metal",
        state: "solid",
        nature: "acidic",
        metallicCharacter: "non-metallic",
        electronicConfig: "[Ar]3d¹⁰4s²4p⁴",
        position: { row: 4, col: 16 }
    },
    {
        name: "Bromine",
        symbol: "Br",
        number: 35,
        mass: 79.904,
        category: "non-metal",
        state: "liquid",
        nature: "acidic",
        metallicCharacter: "non-metallic",
        electronicConfig: "[Ar]3d¹⁰4s²4p⁵",
        position: { row: 4, col: 17 }
    },
    {
        name: "Krypton",
        symbol: "Kr",
        number: 36,
        mass: 83.798,
        category: "noble-gas",
        state: "gas",
        nature: "neutral",
        metallicCharacter: "non-metallic",
        electronicConfig: "[Ar]3d¹⁰4s²4p⁶",
        position: { row: 4, col: 18 }
    },
    // Period 5
    {
        name: "Rubidium",
        symbol: "Rb",
        number: 37,
        mass: 85.468,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Kr]5s¹",
        position: { row: 5, col: 1 }
    },
    {
        name: "Strontium",
        symbol: "Sr",
        number: 38,
        mass: 87.62,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Kr]5s²",
        position: { row: 5, col: 2 }
    },
    // Continue with more elements...
    {
        name: "Yttrium",
        symbol: "Y",
        number: 39,
        mass: 88.906,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Kr]4d¹5s²",
        position: { row: 5, col: 3 }
    },
    // Add more elements...
    {
        name: "Zirconium",
        symbol: "Zr",
        number: 40,
        mass: 91.224,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Kr]4d²5s²",
        position: { row: 5, col: 4 }
    },
    // Adding more elements from Period 5
    {
        name: "Niobium",
        symbol: "Nb",
        number: 41,
        mass: 92.906,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Kr]4d⁴5s¹",
        position: { row: 5, col: 5 }
    },
    {
        name: "Molybdenum",
        symbol: "Mo",
        number: 42,
        mass: 95.95,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Kr]4d⁵5s¹",
        position: { row: 5, col: 6 }
    },
    {
        name: "Technetium",
        symbol: "Tc",
        number: 43,
        mass: 98,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Kr]4d⁵5s²",
        position: { row: 5, col: 7 }
    },
    {
        name: "Ruthenium",
        symbol: "Ru",
        number: 44,
        mass: 101.07,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Kr]4d⁷5s¹",
        position: { row: 5, col: 8 }
    },
    {
        name: "Rhodium",
        symbol: "Rh",
        number: 45,
        mass: 102.91,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Kr]4d⁸5s¹",
        position: { row: 5, col: 9 }
    },
    {
        name: "Palladium",
        symbol: "Pd",
        number: 46,
        mass: 106.42,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Kr]4d¹⁰",
        position: { row: 5, col: 10 }
    },
    {
        name: "Silver",
        symbol: "Ag",
        number: 47,
        mass: 107.87,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Kr]4d¹⁰5s¹",
        position: { row: 5, col: 11 }
    },
    {
        name: "Cadmium",
        symbol: "Cd",
        number: 48,
        mass: 112.41,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Kr]4d¹⁰5s²",
        position: { row: 5, col: 12 }
    },
    {
        name: "Indium",
        symbol: "In",
        number: 49,
        mass: 114.82,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Kr]4d¹⁰5s²5p¹",
        position: { row: 5, col: 13 }
    },
    {
        name: "Tin",
        symbol: "Sn",
        number: 50,
        mass: 118.71,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Kr]4d¹⁰5s²5p²",
        position: { row: 5, col: 14 }
    },
    {
        name: "Antimony",
        symbol: "Sb",
        number: 51,
        mass: 121.76,
        category: "metalloid",
        state: "solid",
        nature: "acidic",
        metallicCharacter: "metalloid",
        electronicConfig: "[Kr]4d¹⁰5s²5p³",
        position: { row: 5, col: 15 }
    },
    {
        name: "Tellurium",
        symbol: "Te",
        number: 52,
        mass: 127.60,
        category: "metalloid",
        state: "solid",
        nature: "acidic",
        metallicCharacter: "metalloid",
        electronicConfig: "[Kr]4d¹⁰5s²5p⁴",
        position: { row: 5, col: 16 }
    },
    {
        name: "Iodine",
        symbol: "I",
        number: 53,
        mass: 126.90,
        category: "non-metal",
        state: "solid",
        nature: "acidic",
        metallicCharacter: "non-metallic",
        electronicConfig: "[Kr]4d¹⁰5s²5p⁵",
        position: { row: 5, col: 17 }
    },
    {
        name: "Xenon",
        symbol: "Xe",
        number: 54,
        mass: 131.29,
        category: "noble-gas",
        state: "gas",
        nature: "neutral",
        metallicCharacter: "non-metallic",
        electronicConfig: "[Kr]4d¹⁰5s²5p⁶",
        position: { row: 5, col: 18 }
    },
    // Period 6
    {
        name: "Cesium",
        symbol: "Cs",
        number: 55,
        mass: 132.91,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]6s¹",
        position: { row: 6, col: 1 }
    },
    {
        name: "Barium",
        symbol: "Ba",
        number: 56,
        mass: 137.33,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]6s²",
        position: { row: 6, col: 2 }
    },
    // Continue with more elements...
    {
        name: "Lanthanum",
        symbol: "La",
        number: 57,
        mass: 138.91,
        category: "lanthanide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]5d¹6s²",
        position: { row: 8, col: 3 }
    },
    // Adding more elements from Period 6
    {
        name: "Hafnium",
        symbol: "Hf",
        number: 72,
        mass: 178.49,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f¹⁴5d²6s²",
        position: { row: 6, col: 4 }
    },
    {
        name: "Tantalum",
        symbol: "Ta",
        number: 73,
        mass: 180.95,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f¹⁴5d³6s²",
        position: { row: 6, col: 5 }
    },
    {
        name: "Tungsten",
        symbol: "W",
        number: 74,
        mass: 183.84,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f¹⁴5d⁴6s²",
        position: { row: 6, col: 6 }
    },
    {
        name: "Rhenium",
        symbol: "Re",
        number: 75,
        mass: 186.21,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f¹⁴5d⁵6s²",
        position: { row: 6, col: 7 }
    },
    {
        name: "Osmium",
        symbol: "Os",
        number: 76,
        mass: 190.23,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f¹⁴5d⁶6s²",
        position: { row: 6, col: 8 }
    },
    {
        name: "Iridium",
        symbol: "Ir",
        number: 77,
        mass: 192.22,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f¹⁴5d⁷6s²",
        position: { row: 6, col: 9 }
    },
    {
        name: "Platinum",
        symbol: "Pt",
        number: 78,
        mass: 195.08,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f¹⁴5d⁹6s¹",
        position: { row: 6, col: 10 }
    },
    {
        name: "Gold",
        symbol: "Au",
        number: 79,
        mass: 196.97,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f¹⁴5d¹⁰6s¹",
        position: { row: 6, col: 11 }
    },
    {
        name: "Mercury",
        symbol: "Hg",
        number: 80,
        mass: 200.59,
        category: "metal",
        state: "liquid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f¹⁴5d¹⁰6s²",
        position: { row: 6, col: 12 }
    },
    {
        name: "Thallium",
        symbol: "Tl",
        number: 81,
        mass: 204.38,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f¹⁴5d¹⁰6s²6p¹",
        position: { row: 6, col: 13 }
    },
    {
        name: "Lead",
        symbol: "Pb",
        number: 82,
        mass: 207.2,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f¹⁴5d¹⁰6s²6p²",
        position: { row: 6, col: 14 }
    },
    {
        name: "Bismuth",
        symbol: "Bi",
        number: 83,
        mass: 208.98,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f¹⁴5d¹⁰6s²6p³",
        position: { row: 6, col: 15 }
    },
    {
        name: "Polonium",
        symbol: "Po",
        number: 84,
        mass: 209,
        category: "metalloid",
        state: "solid",
        nature: "acidic",
        metallicCharacter: "metalloid",
        electronicConfig: "[Xe]4f¹⁴5d¹⁰6s²6p⁴",
        position: { row: 6, col: 16 }
    },
    {
        name: "Astatine",
        symbol: "At",
        number: 85,
        mass: 210,
        category: "metalloid",
        state: "solid",
        nature: "acidic",
        metallicCharacter: "metalloid",
        electronicConfig: "[Xe]4f¹⁴5d¹⁰6s²6p⁵",
        position: { row: 6, col: 17 }
    },
    {
        name: "Radon",
        symbol: "Rn",
        number: 86,
        mass: 222,
        category: "noble-gas",
        state: "gas",
        nature: "neutral",
        metallicCharacter: "non-metallic",
        electronicConfig: "[Xe]4f¹⁴5d¹⁰6s²6p⁶",
        position: { row: 6, col: 18 }
    },
    // Period 7
    {
        name: "Francium",
        symbol: "Fr",
        number: 87,
        mass: 223,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]7s¹",
        position: { row: 7, col: 1 }
    },
    {
        name: "Radium",
        symbol: "Ra",
        number: 88,
        mass: 226,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]7s²",
        position: { row: 7, col: 2 }
    },
    {
        name: "Actinium",
        symbol: "Ac",
        number: 89,
        mass: 227,
        category: "actinide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]6d¹7s²",
        position: { row: 9, col: 3 }
    },
    {
        name: "Rutherfordium",
        symbol: "Rf",
        number: 104,
        mass: 267,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f¹⁴6d²7s²",
        position: { row: 7, col: 4 }
    },
    {
        name: "Dubnium",
        symbol: "Db",
        number: 105,
        mass: 268,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f¹⁴6d³7s²",
        position: { row: 7, col: 5 }
    },
    {
        name: "Seaborgium",
        symbol: "Sg",
        number: 106,
        mass: 269,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f¹⁴6d⁴7s²",
        position: { row: 7, col: 6 }
    },
    {
        name: "Bohrium",
        symbol: "Bh",
        number: 107,
        mass: 270,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f¹⁴6d⁵7s²",
        position: { row: 7, col: 7 }
    },
    {
        name: "Hassium",
        symbol: "Hs",
        number: 108,
        mass: 269,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f¹⁴6d⁶7s²",
        position: { row: 7, col: 8 }
    },
    {
        name: "Meitnerium",
        symbol: "Mt",
        number: 109,
        mass: 278,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f¹⁴6d⁷7s²",
        position: { row: 7, col: 9 }
    },
    {
        name: "Darmstadtium",
        symbol: "Ds",
        number: 110,
        mass: 281,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f¹⁴6d⁸7s²",
        position: { row: 7, col: 10 }
    },
    {
        name: "Roentgenium",
        symbol: "Rg",
        number: 111,
        mass: 282,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f¹⁴6d⁹7s²",
        position: { row: 7, col: 11 }
    },
    {
        name: "Copernicium",
        symbol: "Cn",
        number: 112,
        mass: 285,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f¹⁴6d¹⁰7s²",
        position: { row: 7, col: 12 }
    },
    {
        name: "Nihonium",
        symbol: "Nh",
        number: 113,
        mass: 286,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f¹⁴6d¹⁰7s²7p¹",
        position: { row: 7, col: 13 }
    },
    {
        name: "Flerovium",
        symbol: "Fl",
        number: 114,
        mass: 289,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f¹⁴6d¹⁰7s²7p²",
        position: { row: 7, col: 14 }
    },
    {
        name: "Moscovium",
        symbol: "Mc",
        number: 115,
        mass: 290,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f¹⁴6d¹⁰7s²7p³",
        position: { row: 7, col: 15 }
    },
    {
        name: "Livermorium",
        symbol: "Lv",
        number: 116,
        mass: 293,
        category: "metal",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f¹⁴6d¹⁰7s²7p⁴",
        position: { row: 7, col: 16 }
    },
    {
        name: "Tennessine",
        symbol: "Ts",
        number: 117,
        mass: 294,
        category: "metalloid",
        state: "solid",
        nature: "acidic",
        metallicCharacter: "metalloid",
        electronicConfig: "[Rn]5f¹⁴6d¹⁰7s²7p⁵",
        position: { row: 7, col: 17 }
    },
    {
        name: "Oganesson",
        symbol: "Og",
        number: 118,
        mass: 294,
        category: "noble-gas",
        state: "solid",
        nature: "neutral",
        metallicCharacter: "non-metallic",
        electronicConfig: "[Rn]5f¹⁴6d¹⁰7s²7p⁶",
        position: { row: 7, col: 18 }
    },
    // Lanthanides (row 8, col 4-17)
    {
        name: "Cerium",
        symbol: "Ce",
        number: 58,
        mass: 140.12,
        category: "lanthanide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f¹5d¹6s²",
        position: { row: 8, col: 4 }
    },
    {
        name: "Praseodymium",
        symbol: "Pr",
        number: 59,
        mass: 140.91,
        category: "lanthanide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f³6s²",
        position: { row: 8, col: 5 }
    },
    {
        name: "Neodymium",
        symbol: "Nd",
        number: 60,
        mass: 144.24,
        category: "lanthanide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f⁴6s²",
        position: { row: 8, col: 6 }
    },
    {
        name: "Promethium",
        symbol: "Pm",
        number: 61,
        mass: 145,
        category: "lanthanide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f⁵6s²",
        position: { row: 8, col: 7 }
    },
    {
        name: "Samarium",
        symbol: "Sm",
        number: 62,
        mass: 150.36,
        category: "lanthanide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f⁶6s²",
        position: { row: 8, col: 8 }
    },
    {
        name: "Europium",
        symbol: "Eu",
        number: 63,
        mass: 151.96,
        category: "lanthanide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f⁷6s²",
        position: { row: 8, col: 9 }
    },
    {
        name: "Gadolinium",
        symbol: "Gd",
        number: 64,
        mass: 157.25,
        category: "lanthanide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f⁷5d¹6s²",
        position: { row: 8, col: 10 }
    },
    {
        name: "Terbium",
        symbol: "Tb",
        number: 65,
        mass: 158.93,
        category: "lanthanide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f⁹6s²",
        position: { row: 8, col: 11 }
    },
    {
        name: "Dysprosium",
        symbol: "Dy",
        number: 66,
        mass: 162.50,
        category: "lanthanide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f¹⁰6s²",
        position: { row: 8, col: 12 }
    },
    {
        name: "Holmium",
        symbol: "Ho",
        number: 67,
        mass: 164.93,
        category: "lanthanide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f¹¹6s²",
        position: { row: 8, col: 13 }
    },
    {
        name: "Erbium",
        symbol: "Er",
        number: 68,
        mass: 167.26,
        category: "lanthanide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f¹²6s²",
        position: { row: 8, col: 14 }
    },
    {
        name: "Thulium",
        symbol: "Tm",
        number: 69,
        mass: 168.93,
        category: "lanthanide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f¹³6s²",
        position: { row: 8, col: 15 }
    },
    {
        name: "Ytterbium",
        symbol: "Yb",
        number: 70,
        mass: 173.05,
        category: "lanthanide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f¹⁴6s²",
        position: { row: 8, col: 16 }
    },
    {
        name: "Lutetium",
        symbol: "Lu",
        number: 71,
        mass: 174.97,
        category: "lanthanide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Xe]4f¹⁴5d¹6s²",
        position: { row: 8, col: 17 }
    },
    // Actinides (row 9, col 4-17)
    {
        name: "Thorium",
        symbol: "Th",
        number: 90,
        mass: 232.04,
        category: "actinide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]6d²7s²",
        position: { row: 9, col: 4 }
    },
    {
        name: "Protactinium",
        symbol: "Pa",
        number: 91,
        mass: 231.04,
        category: "actinide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f²6d¹7s²",
        position: { row: 9, col: 5 }
    },
    {
        name: "Uranium",
        symbol: "U",
        number: 92,
        mass: 238.03,
        category: "actinide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f³6d¹7s²",
        position: { row: 9, col: 6 }
    },
    {
        name: "Neptunium",
        symbol: "Np",
        number: 93,
        mass: 237,
        category: "actinide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f⁴6d¹7s²",
        position: { row: 9, col: 7 }
    },
    {
        name: "Plutonium",
        symbol: "Pu",
        number: 94,
        mass: 244,
        category: "actinide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f⁶7s²",
        position: { row: 9, col: 8 }
    },
    {
        name: "Americium",
        symbol: "Am",
        number: 95,
        mass: 243,
        category: "actinide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f⁷7s²",
        position: { row: 9, col: 9 }
    },
    {
        name: "Curium",
        symbol: "Cm",
        number: 96,
        mass: 247,
        category: "actinide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f⁷6d¹7s²",
        position: { row: 9, col: 10 }
    },
    {
        name: "Berkelium",
        symbol: "Bk",
        number: 97,
        mass: 247,
        category: "actinide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f⁹7s²",
        position: { row: 9, col: 11 }
    },
    {
        name: "Californium",
        symbol: "Cf",
        number: 98,
        mass: 251,
        category: "actinide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f¹⁰7s²",
        position: { row: 9, col: 12 }
    },
    {
        name: "Einsteinium",
        symbol: "Es",
        number: 99,
        mass: 252,
        category: "actinide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f¹¹7s²",
        position: { row: 9, col: 13 }
    },
    {
        name: "Fermium",
        symbol: "Fm",
        number: 100,
        mass: 257,
        category: "actinide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f¹²7s²",
        position: { row: 9, col: 14 }
    },
    {
        name: "Mendelevium",
        symbol: "Md",
        number: 101,
        mass: 258,
        category: "actinide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f¹³7s²",
        position: { row: 9, col: 15 }
    },
    {
        name: "Nobelium",
        symbol: "No",
        number: 102,
        mass: 259,
        category: "actinide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f¹⁴7s²",
        position: { row: 9, col: 16 }
    },
    {
        name: "Lawrencium",
        symbol: "Lr",
        number: 103,
        mass: 266,
        category: "actinide",
        state: "solid",
        nature: "basic",
        metallicCharacter: "metallic",
        electronicConfig: "[Rn]5f¹⁴7s²7p¹",
        position: { row: 9, col: 17 }
    }
];

// Export the elements array
export default elements; 